### ISSUE TITLE
SvelteKit build failing

### ISSUE THREAD

**Issue by thecritic** [pablo-abc/felte#112]
**Describe the bug**
Building a SvelteKit project with minimal felte setup is failing (minimal reproduction repository below).
Upon running `npm run build`, I get the following error:

```
file:///tmp/test-app/node_modules/@felte/common/dist/esm/utils/deepSet.js:1
import { __rest } from '../node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.es6.js';
         ^^^^^^
SyntaxError: Named export '__rest' not found. The requested module '../node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.es6.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '../node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.es6.js';
const { __rest } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:104:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:149:5)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Promise.all (index 1)
    at async respond$1 (file:///tmp/test-app/.svelte-kit/output/server/index.js:1480:13)
    at async render_page (file:///tmp/test-app/.svelte-kit/output/server/index.js:1653:20)
    at async resolve (file:///tmp/test-app/.svelte-kit/output/server/index.js:1848:105)
    at async Object.handle (file:///tmp/test-app/.svelte-kit/output/server/index.js:1934:20)
    at async respond (file:///tmp/test-app/.svelte-kit/output/server/index.js:1771:22)
    at async visit (file:///tmp/test-app/node_modules/@sveltejs/kit/dist/chunks/index2.js:1076:20)
> 500 /
    at file:///tmp/test-app/node_modules/@sveltejs/kit/dist/chunks/index2.js:975:11
    at save (file:///tmp/test-app/node_modules/@sveltejs/kit/dist/chunks/index2.js:1194:4)
    at visit (file:///tmp/test-app/node_modules/@sveltejs/kit/dist/chunks/index2.js:1085:3)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**To Reproduce**
1. Check out sample project https://github.com/thecritic/felte-minimal-repro
2. `npm install`
3. Run `npm run build`

**Expected behavior**
Setup should correctly build the SvelteKit app.

**Environment (please complete the following information):**
 - Arch Linux
 - Version: 
    @felte/common^1.0.2
    @felte/reporter-svelte^1.0.2
    @felte/validator-zod^1.0.3

Just found this, probably related to vite handling of CommonJS modules https://github.com/sveltejs/kit/issues/928

**Comment by thecritic** [comment]
Adding the following to `svelte.config.js` seems to have fixed the issue.

```
vite: {
  ssr: {
    noExternal: ['@felte/common']
  }
}
```

**Comment by thecritic** [comment]
This probably has to do with vite trying to [externalize the module for SSR](https://vitejs.dev/guide/ssr.html#ssr-externals) due to the CommonJS import, but I'm not sure about that hypothesis at all...

**Comment by pablo-abc** [comment]
Hi! Is there a reason you're trying to use '@felte/common'? The package for Svelte is 'felte'. The common package contains only common utilities used by other packages.

**Comment by thecritic** [comment]
Ah, that makes sense, I had both `@felte/common` and `felte` installed. Removed `@felte/common` and everything works fine, thank you!
