### ISSUE TITLE
Issue with building in version 1.1.6 caused by deepSet.js

### ISSUE THREAD

**Issue by digitaldeus** [pablo-abc/felte#127]
### Describe the bug

When building my sveltekit project, I am getting an error that says

```
import { __rest } from '../node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.es6.js';
         ^^^^^^
SyntaxError: Named export '__rest' not found. The requested module '../node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.es6.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '../node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/tslib.es6.js';
const { __rest } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async Promise.all (index 1)
    at async respond$1 (file:///Users/deusduke/src/ddtrader/packages/svelte/.svelte-kit/output/server/index.js:1463:13)
    at async resolve (file:///Users/deusduke/src/ddtrader/packages/svelte/.svelte-kit/output/server/index.js:1842:105)
    at async Object.handle (file:///Users/deusduke/src/ddtrader/packages/svelte/.svelte-kit/output/server/chunks/hooks-ec7013aa.js:20:20)
    at async respond (file:///Users/deusduke/src/ddtrader/packages/svelte/.svelte-kit/output/server/index.js:1798:22)
    at async visit (file:///Users/deusduke/src/ddtrader/node_modules/@sveltejs/kit/dist/chunks/index2.js:1084:20)
```

### Which package/s are you using?

felte (Svelte), @felte/validator-yup, @felte/reporter-tippy

### Environment

- OS: Mac OS 12.3.1
- Browser: N/A
- Version: felte@1.1.6

### To reproduce

I'm not entirely sure which includes trigger, but I assume just including something from the deepSet file mentioned above will repro the issue

### Additional context

I have discovered a solution which is to add a package.json to `node_modules/@felte/common/dist/esm/node_modules/.pnpm/tslib@2.3.1/node_modules/tslib/package.json` that declares it type module

```
{
  "type": "module"
}
```

Then the error goes away

**Comment by pablo-abc** [comment]
Hey! Is this a freshly installed SvelteKit project? I just tried this with the adapter-node and adapter-static and can't reproduce this. I do think I know _why_ this might be happening, though. But more information would be nice!


Does it work fine if you go back to 1.1.5?

**Comment by pablo-abc** [comment]
Scratch that, I did manage to reproduce it. I'll look into this! Thanks for reporting this

**Comment by pablo-abc** [comment]
Can you try the latest versions of all three packages? Just pushed a patch for them. So, `felte@1.1.7`, `@felte/validator-yup@1.0.5` and `@felte/reporter-tippy@1.0.7`.

**Comment by digitaldeus** [comment]
That fixed it!  Thanks for the quick patch what was the issue?

**Comment by pablo-abc** [comment]
So, I had realised some packages were bundling the `@felte/common` package, which meant that some code duplication could happen when using multiple `@felte/*` packages. On fixing this it seems other dependencies on `node_modules` were also published. And since npm ignores any directory called `node_modules` this meant it was working locally for me, but not if you installed from npm 😅. Fun stuff.
