### ISSUE TITLE
Error: Function called outside component initialization in SvelteKit with Zod validator

### ISSUE THREAD

**Issue by romelperez** [pablo-abc/felte#201]
### Describe the bug

In a custom component when using `createForm` from the `felte` package, in SvelteKit, there is this error which breaks the application.

```txt
Error: Function called outside component initialization
    at get_current_component (/Users/romelperez/projects/landup/landup-app/node_modules/svelte/internal/index.js:987:15)
    at Object.onDestroy (/Users/romelperez/projects/landup/landup-app/node_modules/svelte/internal/index.js:1029:5)
    at Proxy.createForm (/Users/romelperez/projects/landup/landup-app/node_modules/felte/dist/cjs/index.cjs:40:12)
```

I saw this issue https://github.com/pablo-abc/felte/issues/31 but we are not using it outside of Svelte nor with other packages, only local environment with SvelteKit and the mentioned packages.

### Which package/s are you using?

felte (Svelte), @felte/validator-zod

### Environment

- OS: Mac OS M1
- Browser: Google Chrome 107
- Versions:
```json
"dependencies": {
  "@felte/validator-zod": "^1.0.12",
  "felte": "^1.2.6",
  "zod": "^3.19.1",
  "@sveltejs/kit": "1.0.0-next.555",
  "svelte": "^3.53.1",
  "svelte-check": "^2.9.2",
  "svelte-preprocess": "^4.10.7"
}
```

### To reproduce

```svelte
<script lang="ts">
import { createForm } from 'felte';
import { validator } from '@felte/validator-zod';
import * as zod from 'zod';

const formSchema = zod.object({
  firstName: zod.string().min(1).max(250),
  lastName: zod.string().min(1).max(250)
});

const { form, errors } = createForm({
  extend: validator({ schema: formSchema })
});
</script>

<form use:form>
  <input name="firstName" />
  <input name="lastName" />
  <button type="submit">Submit</button>
</form>
```

### Additional context

Thank you for your work!

**Comment by winston0410** [comment]
I am having this issue as well, have you solved this @romelperez ?

**Comment by romelperez** [comment]
@winston0410 , I couldn't work around it so I had to use another solution. Still waiting for a response about this here.

**Comment by winston0410** [comment]
@romelperez  I have been using `app/environment` to resolve this, but it is definitely not optimal.

```svelte
<script lang="ts" context="module">
import { browser } from '$app/environment';
</script>
                    {#if browser}
                        <-- a component contains all logic  of felte -->
                        <ProductForm />
                    {/if}
```

I hope this can be fixed, because I think felte is the most feature rich form library out there

**Comment by romelperez** [comment]
@winston0410 , we created our own solution with a pretty close API to that of Felte, but with just a few features, so if Felte is usable again, we can switch to it.

**Comment by winston0410** [comment]
@pablo-abc no worries! Thank you for your great work with this library! I will try an make a reproducible example for you later today

**Comment by winston0410** [comment]
I tried to reproduce this issue, commented out everything unrelated and make sure version are correct, but still with no luck, I think I will need some input from you @romelperez to reproduce the issue . My attempt is over here
https://github.com/winston0410/felte-repo

I got this error when I work with a SvelteKit application in a monorepo(Nx repo), were you using a monorepo as well?

**Comment by winston0410** [comment]
Ok I am able to reproduce this, and I think this is not an issue from `felte` but monorepo, but I have no idea why only `felte` has the issue, and the solution. 

https://github.com/winston0410/felte-repo/tree/9a00ea259e62b2c1be86436cf0f20908fff179ba

**Comment by romelperez** [comment]
In our case, we are using a root folder SvelteKit application. If we have time, we will try to reproduce this again, since we moved to another solution, but I like this library too.

**Comment by winston0410** [comment]
@romelperez somehow I just got an idea and I have solved the issue by guess this morning. I am using Vite and this is needed in the config for `felte` to work:

```typescript
import type { UserConfig } from 'vite'

const config: UserConfig = {
	ssr: {
		format: "esm",
		noExternal: ["felte"]
	}
};

export default config;
```

If you are using `vite`, this should solve your issue as well!

**Comment by fnimick** [comment]
I can confirm the above fix also resolves the problem I was having with crashes in SSR, in my case I was using a monorepo with lerna.
