### ISSUE TITLE
Error importing yup: `TypeError: Line must be greater than or equal to 1, got -1`

### ISSUE THREAD

**Issue by websocket98765** [pablo-abc/felte#8]
Sorry. I don't know what changed, maybe Svelte Kit did. But even importing yup (without using it or using a reporter) causes the build to fail now.

Error:

```sh
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/Users/me/my-app/node_modules/vite/dist/node/chunks/dep-efe32886.js:67770:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/me/my-app/node_modules/vite/dist/node/chunks/dep-efe32886.js:67839:22)
    at /Users/me/my-app/node_modules/vite/dist/node/chunks/dep-efe32886.js:68799:34
    at String.replace (<anonymous>)
    at /Users/me/my-app/node_modules/vite/dist/node/chunks/dep-efe32886.js:68789:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/me/my-app/node_modules/vite/dist/node/chunks/dep-efe32886.js:68788:10)
    at Object.ssrFixStacktrace (/Users/me/my-app/node_modules/vite/dist/node/chunks/dep-efe32886.js:69043:27)
    at Object.get_stack (file:///Users/me/my-app/node_modules/@sveltejs/kit/dist/chunks/index.js:3359:28)
    at get_response (file:///Users/me/my-app/node_modules/@sveltejs/kit/dist/ssr.js:2272:32)
```

Repro. Comment & un-comment the yup import to see it work or break:
```svelte
<script context="module">
  import { createForm } from 'felte';
  import reporterDom from '@felte/reporter-dom';
  // import { validateSchema } from '@felte/validator-yup';
  // import * as yup from 'yup'; //  << this line

  // const schema = yup.object({
  //   email: yup.string().email().required(),
  //   message: yup.string().required()
  // });

  const { form } = createForm({
    extend: reporterDom(),
    onSubmit: (values) => {
      console.log('values', values);
    }
    // validate: validateSchema(schema)
  });
</script>

<h1>Contact</h1>

<form use:form>
  <label for="email">Email</label>
  <input
    id="email"
    type="text"
    name="email"
    aria-describedby="email-validation"
  />
  <div
    id="email-validation"
    data-felte-reporter-dom-for="email"
    aria-live="polite"
  />

  <label for="message">Message</label>
  <input
    id="message"
    type="text"
    name="message"
    aria-describedby="message-validation"
  />
  <div
    id="message-validation"
    data-felte-reporter-dom-for="message"
    aria-live="polite"
  />

  <button type="submit">submit</button>
</form>
```

package.json
```json
	"devDependencies": {
		"@sveltejs/adapter-node": "next",
		"@sveltejs/kit": "next",
		"autoprefixer": "^10.2.5",
		"cssnano": "^4.1.10",
		"postcss": "^8.2.7",
		"postcss-load-config": "^3.0.1",
		"svelte": "^3.29.0",
		"svelte-preprocess": "^4.6.9",
		"vite": "^2.1.0"
	},
	"type": "module",
	"engines": {
		"node": ">= 12.17.0"
	},
	"dependencies": {
		"@felte/reporter-dom": "^0.1.9",
		"@felte/validator-yup": "^0.1.0",
		"felte": "^0.5.3",
		"yup": "^0.32.9"
	}
```

**Comment by pablo-abc** [comment]
Sadly I'm not that familiar with SvelteKit. I haven't experimented with it yet.

Buuuut from what I've read... does it work if you move `yup` to `devDependencies`?

Another question, why are you using everything inside of a `context=module` script? 😮 I haven't personally tested if that works 🤔

**Comment by websocket98765** [comment]
> Another question, why are you using everything inside of a context=module script? 😮 I haven't personally tested if that works 🤔

My bad. Ignore that. I tried many things to get it working again. It works either way for that part.

> does it work if you move yup to devDependencies

This was it!!  I moved it to `dependencies` because I wanted to share the schema for client-side and server-side validation. (I still need to try that.) But the error is gone by moving it to devDependencies. Thanks!
